name: Ubuntu_Cloudflare_QuickTunnel

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Desktop Environment
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies tightvncserver
          
      - name: Install noVNC
        run: |
          git clone https://github.com/novnc/noVNC.git
          cp noVNC/vnc.html noVNC/index.html
          
      - name: Install Cloudflared
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb

      - name: Setup VNC and Quick Tunnel
        run: |
          # Thiết lập mật khẩu VNC là 123456
          mkdir -p ~/.vnc
          echo "123456" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          tightvncserver :1
          
          # Chạy noVNC proxy
          ./noVNC/utils/novnc_proxy --vnc localhost:5901 --listen 6080 &
          
          # Kích hoạt Quick Tunnel
          echo "Đợi một lát để lấy URL..."
          cloudflared tunnel --url http://localhost:6080
